### ISSUE TITLE
providing interaction features while training

### ISSUE THREAD

**Issue by fenneccat** [AIM-SE/DIF-SR#9]
Thank you for the great code that you provide.

I wanted to give a float-type feature like a rating in the training step.
I checked your code and it seems it only considers token-type features.
Did I understand correctly?

Thank you

**Comment by PALIN2018** [comment]
Hi fenneccat,

Thank you for your interest in our project and for bringing up the issue regarding the side information used in our experiments. We really appreciate your feedback and would like to provide some clarification.

In our experiments, we mainly used categorical side information for DIF because we found that it had a more significant impact on SR performance. However, if you would like to use float-type side information, recbole also supports this feature. We encourage you to try it out and provide feedback if you encounter any issues.

Thank you again for your contribution to our project, and please don't hesitate to reach out to us if you have any further questions or comments.

**Comment by dcy0577** [comment]
Hi, in my custom dataset the user and item features are in matrix format(e.g. some numpy arrays), which part of code can I adjust to handle such features?

**Comment by zyx1017** [comment]
@PALIN2018 Hello，when I try to give a float-type feature like a pricein the training step. It have a mistake in the 80 line in sasrecd.py：
` self.n_attributes = {}
        for attribute in self.selected_features:
            **self.n_attributes[attribute] = len(dataset.field2token_id[attribute])**
        if self.attribute_predictor == 'MLP':`

It seems that can not get the len of the float-feature in recbole.
how can I solve thie problem.

**Comment by zyx1017** [comment]
@PALIN2018 
 In addition to exploring the impact of selecting which attributes on the yelp dataset, which attributes are selected separately for each dataset when comparing to the baseline model? I noticed that only the Categories attribute was selected in the configuration files, is this the case?
